---
title: "plotly examples"
author: "Sibei Liu"
date: "2019/10/17"
output: html_document
---


```{r}
data("nyc_airbnb")
```

```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

```{r}
set.seed(1)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  sample_n(5000)
```

```{r}
nyc_airbnb %>%
  plot_ly(x=~lat,y=~long,typr="scatter",mode="markers",color=~price,alpha=.5)
```

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(
    neighbourhood=fct_reorder(neighbourhood,n)
  ) %>% 
  plot_ly(x=~neighbourhood,y=~n,type="bar")
```
yes

